// auto-generated by render.cjs
module.exports = {
  "SLIDES": [
    "slides/slide-01.html",
    "slides/slide-02.html",
    "slides/slide-03.html",
    "slides/slide-04.html",
    "slides/slide-05.html",
    "slides/slide-06.html",
    "slides/slide-07.html",
    "slides/slide-08.html"
  ],
  "OUTPUT_FILE": "gcon-levelup.pptx",
  "DECK_TITLE": "GCON Level Up 브랜드 제안",
  "DECK_AUTHOR": "CHATdaeri"
};
