// auto-generated by render.cjs
module.exports = {
  "SLIDES": [
    "slides/slide-01.html",
    "slides/slide-02.html",
    "slides/slide-03.html",
    "slides/slide-04.html",
    "slides/slide-05.html",
    "slides/slide-06.html",
    "slides/slide-07.html",
    "slides/slide-08.html",
    "slides/slide-09.html"
  ],
  "OUTPUT_FILE": "real-estate-proposal.pptx",
  "DECK_TITLE": "S시 K동 오피스텔 분양성 검토",
  "DECK_AUTHOR": "CHATdaeri"
};
