// auto-generated by render.cjs
module.exports = {
  "SLIDES": [
    "slides/slide-01.html",
    "slides/slide-02.html",
    "slides/slide-03.html",
    "slides/slide-04.html",
    "slides/slide-05.html",
    "slides/slide-06.html",
    "slides/slide-07.html",
    "slides/slide-08.html",
    "slides/slide-09.html"
  ],
  "OUTPUT_FILE": "dx-proposal-demo.pptx",
  "DECK_TITLE": "DX 솔루션 도입 제안서",
  "DECK_AUTHOR": "CHATdaeri"
};
